service: lbh-project-finder

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false
  region: eu-west-2
  stage: ${opt:stage}

package:
  individually: true
  exclude:
    - ./**

functions:
  project-finder:
    name: ${self:service}-${self:provider.stage}
    handler: lambda.handler
    timeout: 30
    package:
      include:
        - lambda.js
        - next.config.js
        - pages/**
        - public/**
        - build/_next/**
        - node_modules/**
    events:
      - http:
          path: api/{proxy+}
          method: ANY
      - http: ANY /
      - http: ANY /{proxy+}
    provisionedConcurrency: 5
    vpc:
      securityGroupIds: ${self:custom.securityGroups.${self:provider.stage}}
      subnetIds: ${self:custom.subnets.${self:provider.stage}}
    environment:
      API_KEY: ${ssm:/project-finder-front-end/${self:provider.stage}/api-key~true}
      ENDPOINT_API: ${ssm:/project-finder-front-end/${self:provider.stage}/endpoint-api}
      GSSO_URL: ${ssm:/project-finder-front-end/${self:provider.stage}/gsso-url}
      GSSO_TOKEN_NAME: ${ssm:/project-finder-front-end/${self:provider.stage}/gsso-token-name}
      HACKNEY_JWT_SECRET: ${ssm:/project-finder-front-end/${self:provider.stage}/hackney-jwt}
      AUTHORISED_USER_GROUP: ${ssm:/project-finder-front-end/${self:provider.stage}/authorised-user-group}
      AUTHORISED_ADMIN_GROUP: ${ssm:/project-finder-front-end/${self:provider.stage}/authorised-admin-group}
      REDIRECT_URL: ${ssm:/project-finder-front-end/${self:provider.stage}/redirect_url}
resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.aliases.${self:provider.stage}}
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.certificate-arn.${self:provider.stage}}
            MinimumProtocolVersion: TLSv1.2_2018
            SslSupportMethod: sni-only
          DefaultCacheBehavior:
            TargetOriginId: ${self:service}-${self:provider.stage}-custom-origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            DefaultTTL: 0
            MaxTTL: 0
            MinTTL: 0
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: all
          Enabled: true
          Origins:
            - Id: ${self:service}-${self:provider.stage}-custom-origin
              DomainName: ${self:custom.domain-name}
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

custom:
  domain-name:
    Fn::Join:
      - '.'
      - - Ref: ApiGatewayRestApi
        - execute-api
        - eu-west-2
        - amazonaws.com
  aliases:
    development: project-finder-development.hackney.gov.uk
    staging: project-finder-staging.hackney.gov.uk
  certificate-arn:
    development: arn:aws:acm:us-east-1:859159924354:certificate/dbb3198e-b779-41b6-80b3-4ffd5dd19bf4
    staging: arn:aws:acm:us-east-1:715003523189:certificate/8f7fa30c-a4e5-4775-b827-ade824a33c9a
  securityGroups:
    staging:
      - sg-0197fdf49dadd52e7
  subnets:
    staging:
      - subnet-06d3de1bd9181b0d7
      - subnet-0ed7d7713d1127656
    production:
      - subnet-0b7b8fea07efabf34
      - subnet-01d3657f97a243261
